// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1XcwfeQvjDCsC4Oz9S2x8MJrWpucDQA',
    appId: '1:723916768361:web:afb5c220fcdc22ef260ef8',
    messagingSenderId: '723916768361',
    projectId: 'aurahome-5d3f9',
    authDomain: 'aurahome-5d3f9.firebaseapp.com',
    storageBucket: 'aurahome-5d3f9.firebasestorage.app',
    measurementId: 'G-NPFJ06VJ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDdDY5yAkbUkT44izwZMlG7kWeDtaAco',
    appId: '1:723916768361:android:27279261335797be260ef8',
    messagingSenderId: '723916768361',
    projectId: 'aurahome-5d3f9',
    storageBucket: 'aurahome-5d3f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvH2tCTaCRf308N_eukL4Db8ZD3-mdY8',
    appId: '1:723916768361:ios:60076bba146b9a67260ef8',
    messagingSenderId: '723916768361',
    projectId: 'aurahome-5d3f9',
    storageBucket: 'aurahome-5d3f9.firebasestorage.app',
    iosBundleId: 'com.example.aurahome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuvH2tCTaCRf308N_eukL4Db8ZD3-mdY8',
    appId: '1:723916768361:ios:60076bba146b9a67260ef8',
    messagingSenderId: '723916768361',
    projectId: 'aurahome-5d3f9',
    storageBucket: 'aurahome-5d3f9.firebasestorage.app',
    iosBundleId: 'com.example.aurahome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg1XcwfeQvjDCsC4Oz9S2x8MJrWpucDQA',
    appId: '1:723916768361:web:e2db50862746847d260ef8',
    messagingSenderId: '723916768361',
    projectId: 'aurahome-5d3f9',
    authDomain: 'aurahome-5d3f9.firebaseapp.com',
    storageBucket: 'aurahome-5d3f9.firebasestorage.app',
    measurementId: 'G-K9RDZX2NDM',
  );

}